

MQTT_USERNAME: jkct
MQTT_PASSWORD: 310012
MQTT_URL: tcp://172.16.5.20:1883


server:
  port: 31001 # 18091
mqtt:
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  url: ${MQTT_URL}
#  producer:
#    clientId: jkctProducer
#    defaultTopic: testMqttTopic
#  consumer:
#    clientId: jkctConsumer
#    defaultTopic: testMqttTopic